### PR TITLE
[fix] Annotations on exception handler methods do not work

### PR DESCRIPTION
**Pull request by xhaggi**
Fixes gh-150

### CODE REVIEW

**Comment by xhaggi** [comment]
I will do a backport for 3.6.x when it is merged.

**Comment by wimdeblauwe** [comment]
Isn't it easier to first merge this one before #152 then there is no need to backport ?

**Review by wimdeblauwe — APPROVED** [review]

**Comment by xhaggi** [comment]
It doesn't really matter to me. Let's shove that in and I'll do the backport + rebase from #152.

**Comment by xhaggi** [comment]
Merged and backported to [3.6.x](https://github.com/wimdeblauwe/htmx-spring-boot/tree/3.6.x)

**Pull request merged**
