### PR TITLE
Allow HtmxResponse to be used as return type in error handlers

### LINKED ISSUE #94: Support HtmxResponse in error handlers
I would love to be able to use `HtmxResponse` as the return type for error handlers. This would allow to do something like this:

```
@ExceptionHandler(Exception.class)
public HtmxResponse handleError(Exception ex) {
  return HtmxResponse.builder()
      .reswap(HtmxReswap.none())
      .view(new ModelAndView("fragments/flashmessage :: oob-flashmessage-info", Map.of("message", ex.getMessage())))
      .build();
}
```

The idea is that there is a `<div/>` on each page that allows to show a general error message via OOB swap.

As a workaround, I currently do this:

```
@ExceptionHandler(Exception.class)
public ModelAndView handleError(HttpServletResponse response, Exception ex) {
  response.setHeader("HX-Reswap", "none");
  return new ModelAndView("fragments/flashmessage :: oob-flashmessage-warning", Map.of("message", ex.getMessage()));
}
```

 But it would be nicer if we could use `HtmxResponse`.

### PR DESCRIPTION
**Pull request by wimdeblauwe**
This PR adds an `HandlerMethodReturnValueHandler` implementation to handle a `HtmxResponse` object as a return type from an error handler. A lot of code is the same as in `HtmxViewHandlerInterceptor`. For that reason, I extracted `HtmxResponseHelper`.

@dsyer and @odrotbohm Would love you feedback on this PR. Especially doubting if the method calls I am doing in the `HtmxMvcAutoConfiguration` are correct given that `@AutoConfiguration` has `proxyBeanMethods` set to `false`, but I don't know of another way to make it work.

Fixes #94

### CODE REVIEW

**Comment by dsyer** [comment]
Agree about the internal method call. We either need to remove the `proxyBeanMethods` flag or ship them out to a separate `@Configuration` (and wire them back into the constructor).

**Comment by dsyer** [comment]
Isn’t the interceptor mainly doing exactly the same work as the return value handler? I’m not sure it needs to be done twice. (So all the code from the helper could just be migrated to the return value handler?)

**Comment by wimdeblauwe** [comment]
Thanks for the input @dsyer. You are correct that there is no more need for the intercepter, the return value handler works for all cases. I have updated the code accordingly.

**Comment by dsyer** [comment]
LGTM

**Comment by wimdeblauwe** [comment]
This is now released and I blogged to showcase the feature: https://www.wimdeblauwe.com/blog/2023/12/14/htmx-global-error-handler/

**Comment by xhaggi** [comment]
@wimdeblauwe is there a way to restrict the `@ExceptionHandler` to htmx requests only?

**Comment by wimdeblauwe** [comment]
According to https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc/, you can define a HttpServletRequest parameter in your exception handler. You could read the headers there to check if it is an htmx request or not.

**Comment by xhaggi** [comment]
Yeah, I am aware of that. I meant an annotation like the one we have for the controller methods.

**Comment by wimdeblauwe** [comment]
That would be nice if that is possible, but no clue if there are extension points to implement that.

**Pull request merged**
